import { ApiCallState, PagedData } from "../Utils";

export type ProjectVariation = {
  id?: number;
  date: string;
  description: string;
  amount: number;
  document?: any;
  project_id: number;
};

export type ProjectVariationStateTypes = {
  fetchAll: ApiCallState<ProjectVariation[]>;
  fetchOne: ApiCallState<ProjectVariation | {}>;
  fetchPaged: ApiCallState<PagedData<ProjectVariation[]>>;
};

export const ProjectVariationActionTypes = {
  FETCH_ALL_PROJECT_VARIATION: "FETCH_ALL_PROJECT_VARIATION",
  FETCH_ALL_PROJECT_VARIATION_RESET: "FETCH_ALL_PROJECT_VARIATION_RESET",
  FETCH_ALL_PROJECT_VARIATION_FAILURE: "FETCH_ALL_PROJECT_VARIATION_FAILURE",
  FETCH_ALL_PROJECT_VARIATION_SUCCESS: "FETCH_ALL_PROJECT_VARIATION_SUCCESS",

  FETCH_PAGED_PROJECT_VARIATION: "FETCH_PAGED_PROJECT_VARIATION",
  FETCH_PAGED_PROJECT_VARIATION_RESET: "FETCH_PAGED_PROJECT_VARIATION_RESET",
  FETCH_PAGED_PROJECT_VARIATION_FAILURE:
    "FETCH_PAGED_PROJECT_VARIATION_FAILURE",
  FETCH_PAGED_PROJECT_VARIATION_SUCCESS:
    "FETCH_PAGED_PROJECT_VARIATION_SUCCESS",

  FETCH_ONE_PROJECT_VARIATION: "FETCH_ONE_PROJECT_VARIATION",
  FETCH_ONE_PROJECT_VARIATION_RESET: "FETCH_ONE_PROJECT_VARIATION_RESET",
  FETCH_ONE_PROJECT_VARIATION_FAILURE: "FETCH_ONE_PROJECT_VARIATION_FAILURE",
  FETCH_ONE_PROJECT_VARIATION_SUCCESS: "FETCH_ONE_PROJECT_VARIATION_SUCCESS",
};
