import { ApiCallState, PagedData } from "../Utils";

export type MaterialApprovalStatusReport = {
  id?: number;
  date: string;
  type: string;
  ref_no: string;
  description: string;
  manufacturer: string;
  supplier: string;
  consultant_receiving_date: string;
  return_date: string;
  status: string;
  comments: string;
};

export type MaterialApprovalStatusStateTypes = {
  fetchAll: ApiCallState<MaterialApprovalStatusReport[]>;
  fetchOne: ApiCallState<MaterialApprovalStatusReport | {}>;
  fetchPaged: ApiCallState<PagedData<MaterialApprovalStatusReport[]>>;
};

export const MaterialApprovalStatusActionTypes = {
  FETCH_ALL_MATERIAL_APPROVAL_STATUS: "FETCH_ALL_MATERIAL_APPROVAL_STATUS",
  FETCH_ALL_MATERIAL_APPROVAL_STATUS_RESET:
    "FETCH_ALL_MATERIAL_APPROVAL_STATUS_RESET",
  FETCH_ALL_MATERIAL_APPROVAL_STATUS_FAILURE:
    "FETCH_ALL_MATERIAL_APPROVAL_STATUS_FAILURE",
  FETCH_ALL_MATERIAL_APPROVAL_STATUS_SUCCESS:
    "FETCH_ALL_MATERIAL_APPROVAL_STATUS_SUCCESS",

  FETCH_PAGED_MATERIAL_APPROVAL_STATUS: "FETCH_PAGED_MATERIAL_APPROVAL_STATUS",
  FETCH_PAGED_MATERIAL_APPROVAL_STATUS_RESET:
    "FETCH_PAGED_MATERIAL_APPROVAL_STATUS_RESET",
  FETCH_PAGED_MATERIAL_APPROVAL_STATUS_FAILURE:
    "FETCH_PAGED_MATERIAL_APPROVAL_STATUS_FAILURE",
  FETCH_PAGED_MATERIAL_APPROVAL_STATUS_SUCCESS:
    "FETCH_PAGED_MATERIAL_APPROVAL_STATUS_SUCCESS",

  FETCH_ONE_MATERIAL_APPROVAL_STATUS: "FETCH_ONE_MATERIAL_APPROVAL_STATUS",
  FETCH_ONE_MATERIAL_APPROVAL_STATUS_RESET:
    "FETCH_ONE_MATERIAL_APPROVAL_STATUS_RESET",
  FETCH_ONE_MATERIAL_APPROVAL_STATUS_FAILURE:
    "FETCH_ONE_MATERIAL_APPROVAL_STATUS_FAILURE",
  FETCH_ONE_MATERIAL_APPROVAL_STATUS_SUCCESS:
    "FETCH_ONE_MATERIAL_APPROVAL_STATUS_SUCCESS",
};
