import { ApiCallState, PagedData } from "../Utils";

export type Category = {
  id?: number;
  description: string;
};

export type CategoryStateTypes = {
  fetchAll: ApiCallState<Category[]>;
  fetchOne: ApiCallState<Category | {}>;
  fetchPaged: ApiCallState<PagedData<Category[]>>;
};

export const CategoryActionTypes = {
  FETCH_ALL_CATEGORY: "FETCH_ALL_CATEGORY",
  FETCH_ALL_CATEGORY_RESET: "FETCH_ALL_CATEGORY_RESET",
  FETCH_ALL_CATEGORY_FAILURE: "FETCH_ALL_CATEGORY_FAILURE",
  FETCH_ALL_CATEGORY_SUCCESS: "FETCH_ALL_CATEGORY_SUCCESS",

  FETCH_PAGED_CATEGORY: "FETCH_PAGED_CATEGORY",
  FETCH_PAGED_CATEGORY_RESET: "FETCH_PAGED_CATEGORY_RESET",
  FETCH_PAGED_CATEGORY_FAILURE: "FETCH_PAGED_CATEGORY_FAILURE",
  FETCH_PAGED_CATEGORY_SUCCESS: "FETCH_PAGED_CATEGORY_SUCCESS",

  FETCH_ONE_CATEGORY: "FETCH_ONE_CATEGORY",
  FETCH_ONE_CATEGORY_RESET: "FETCH_ONE_CATEGORY_RESET",
  FETCH_ONE_CATEGORY_FAILURE: "FETCH_ONE_CATEGORY_FAILURE",
  FETCH_ONE_CATEGORY_SUCCESS: "FETCH_ONE_CATEGORY_SUCCESS",
};
