export const init_building_boq: any = [
  {
    super_title: "SUB STRUCTURE",
    task_name:
      "Site clearing to remove top soil to an average depth of  20cm starting from N.G.L.",
    title: "EXCAVATION & EARTHWORK",
    sub_title: null,
    item_no: 1.1,
    unit: "M²",
    quantity: 0,
    unit_price: 0,

    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764809,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name:
      "Bulk excavation over the site to reduce ground level up to 1500mm from stripped ground level in ordinary soil excavation.",
    title: "EXCAVATION & EARTHWORK",
    sub_title: null,
    item_no: 1.2,
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764810,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "Ditto with item No. 1.2 but not exceeding 3000mm.",
    title: "EXCAVATION & EARTHWORK",
    sub_title: null,
    item_no: 1.3,
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764811,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name:
      "Pit  excavation for footing of ordinary soil to a depth of 1500mm below reduced ground surface.",
    title: "EXCAVATION & EARTHWORK",
    sub_title: null,
    item_no: 1.4,
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764812,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "Ditto with item No. 1.4 but not exceeding 3000mm.",
    title: "EXCAVATION & EARTHWORK",
    sub_title: null,
    item_no: 1.5,
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764813,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name:
      "Trench  excavation in ordinary soil for stone masonry wall to a depth of 1500mm below reduced ground surface.",
    title: "EXCAVATION & EARTHWORK",
    sub_title: null,
    item_no: 1.6,
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764814,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name:
      "Backfill with borrowed selected material under hardcore well rolled & compacted in layers of 20cm (2 layers)",
    title: "EXCAVATION & EARTHWORK",
    sub_title: null,
    item_no: 1.7,
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764815,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name:
      "Backfill with borrowed selected material in footing and masonry remaining part well rolled & compacted",
    title: "EXCAVATION & EARTHWORK",
    sub_title: null,
    item_no: 1.8,
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764816,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name:
      "25cm thick basaltic stone hardcore well rolled, consolidated and blinded with crushed stone.",
    title: "EXCAVATION & EARTHWORK",
    sub_title: null,
    item_no: 1.9,
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764817,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name:
      "Load & cart away the excavated material to a minimum distance of 5km from the site.",
    title: "EXCAVATION & EARTHWORK",
    sub_title: null,
    item_no: 1.1,
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764818,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "Under Isolated Footing",
    title: "CONCRETE WORK",
    sub_title: "Lean concrete with C-5",
    item_no: "a",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764819,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "Under Stone Masonry Wall",
    title: "CONCRETE WORK",
    sub_title: "Lean concrete with C-5",
    item_no: "b",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764820,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "In isolated footing",
    title: "CONCRETE WORK",
    sub_title:
      "Reinforced concrete in class C-25 filled into formwork and vibrated around steel reinforcement. Steel and formwork measured separately:-",
    item_no: "a",
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764821,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "In Basement floor Beams",
    title: "CONCRETE WORK",
    sub_title:
      "Reinforced concrete in class C-25 filled into formwork and vibrated around steel reinforcement. Steel and formwork measured separately:-",
    item_no: "b",
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764822,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "In Basement floor slab",
    title: "CONCRETE WORK",
    sub_title:
      "Reinforced concrete in class C-25 filled into formwork and vibrated around steel reinforcement. Steel and formwork measured separately:-",
    item_no: "c",
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764823,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "In foundation column and shear walls",
    title: "CONCRETE WORK",
    sub_title:
      "Reinforced concrete in class C-25 filled into formwork and vibrated around steel reinforcement. Steel and formwork measured separately:-",
    item_no: "d",
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764824,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "In Suspended Ground Floor beam",
    title: "CONCRETE WORK",
    sub_title:
      "Reinforced concrete in class C-25 filled into formwork and vibrated around steel reinforcement. Steel and formwork measured separately:-",
    item_no: "e",
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764825,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "In Suspended Ground floor slab",
    title: "CONCRETE WORK",
    sub_title:
      "Reinforced concrete in class C-25 filled into formwork and vibrated around steel reinforcement. Steel and formwork measured separately:-",
    item_no: "f",
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764826,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "To Isolated Footing",
    title: "CONCRETE WORK",
    sub_title: "Provide, cut & fix in position sawn Zigba wood formwork to:-",
    item_no: "a",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764827,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "To Basement Floor Beams",
    title: "CONCRETE WORK",
    sub_title: "Provide, cut & fix in position sawn Zigba wood formwork to:-",
    item_no: "b",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764828,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "To Basement floor slab",
    title: "CONCRETE WORK",
    sub_title: "Provide, cut & fix in position sawn Zigba wood formwork to:-",
    item_no: "c",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764829,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "To foundation column and shear walls",
    title: "CONCRETE WORK",
    sub_title: "Provide, cut & fix in position sawn Zigba wood formwork to:-",
    item_no: "d",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764830,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "To Suspended Ground Floor beam",
    title: "CONCRETE WORK",
    sub_title: "Provide, cut & fix in position sawn Zigba wood formwork to:-",
    item_no: "e",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764831,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "To Suspended Ground floor slab",
    title: "CONCRETE WORK",
    sub_title: "Provide, cut & fix in position sawn Zigba wood formwork to:-",
    item_no: "f",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764832,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "Ø 8 mm. deformed bar",
    title: "CONCRETE WORK",
    sub_title:
      "Steel reinforcement for use in sub structure concrete works with a minimum yield strength Fyk of 460MPa. Reinforcement shall be according to Structural Drawings and Technical Specifications. Price includes cutting bending, placing in position and tying wires.",
    item_no: "a",
    unit: "KG",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764833,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "Ø 10 mm. deformed bar",
    title: "CONCRETE WORK",
    sub_title:
      "Steel reinforcement for use in sub structure concrete works with a minimum yield strength Fyk of 460MPa. Reinforcement shall be according to Structural Drawings and Technical Specifications. Price includes cutting bending, placing in position and tying wires.",
    item_no: "b",
    unit: "KG",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764834,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "Ø 12 mm. deformed bar",
    title: "CONCRETE WORK",
    sub_title:
      "Steel reinforcement for use in sub structure concrete works with a minimum yield strength Fyk of 460MPa. Reinforcement shall be according to Structural Drawings and Technical Specifications. Price includes cutting bending, placing in position and tying wires.",
    item_no: "c",
    unit: "KG",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764835,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "Ø 14 mm. deformed bar",
    title: "CONCRETE WORK",
    sub_title:
      "Steel reinforcement for use in sub structure concrete works with a minimum yield strength Fyk of 460MPa. Reinforcement shall be according to Structural Drawings and Technical Specifications. Price includes cutting bending, placing in position and tying wires.",
    item_no: "d",
    unit: "KG",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764836,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "Ø 16 mm. deformed bar",
    title: "CONCRETE WORK",
    sub_title:
      "Steel reinforcement for use in sub structure concrete works with a minimum yield strength Fyk of 460MPa. Reinforcement shall be according to Structural Drawings and Technical Specifications. Price includes cutting bending, placing in position and tying wires.",
    item_no: "e",
    unit: "KG",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764837,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "Ø 20 mm. deformed bar",
    title: "CONCRETE WORK",
    sub_title:
      "Steel reinforcement for use in sub structure concrete works with a minimum yield strength Fyk of 460MPa. Reinforcement shall be according to Structural Drawings and Technical Specifications. Price includes cutting bending, placing in position and tying wires.",
    item_no: "f",
    unit: "KG",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764838,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "50cm thick below ground level.",
    title: "MASONRY WORK",
    sub_title: null,
    item_no: 2.1,
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764839,
  },
  {
    super_title: "SUB STRUCTURE",
    task_name: "50cm thick above ground level.",
    title: "MASONRY WORK",
    sub_title: null,
    item_no: 2.2,
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764840,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "In Elevation column",
    title: "CONCRETE WORK",
    sub_title:
      "Reinforced concrete in class C-25 filled into formwork and vibrated around steel reinforcement. Steel and formwork measured separately:-",
    item_no: "a",
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764841,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "In Suspended floor slab",
    title: "CONCRETE WORK",
    sub_title:
      "Reinforced concrete in class C-25 filled into formwork and vibrated around steel reinforcement. Steel and formwork measured separately:-",
    item_no: "b",
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764842,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "In Suspended floor beam",
    title: "CONCRETE WORK",
    sub_title:
      "Reinforced concrete in class C-25 filled into formwork and vibrated around steel reinforcement. Steel and formwork measured separately:-",
    item_no: "c",
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764843,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "In Stair case",
    title: "CONCRETE WORK",
    sub_title:
      "Reinforced concrete in class C-25 filled into formwork and vibrated around steel reinforcement. Steel and formwork measured separately:-",
    item_no: "d",
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764844,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "In Roof Slab",
    title: "CONCRETE WORK",
    sub_title:
      "Reinforced concrete in class C-25 filled into formwork and vibrated around steel reinforcement. Steel and formwork measured separately:-",
    item_no: "e",
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764845,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "In Top Tie beam",
    title: "CONCRETE WORK",
    sub_title:
      "Reinforced concrete in class C-25 filled into formwork and vibrated around steel reinforcement. Steel and formwork measured separately:-",
    item_no: "f",
    unit: "M³",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764846,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "In Elevation column",
    title: "CONCRETE WORK",
    sub_title:
      "Provide, cut & fix in position sawn Zigba wood formwork (yellow panels for slab side beams) to:-",
    item_no: "a",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764847,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "In Suspended floor slab",
    title: "CONCRETE WORK",
    sub_title:
      "Provide, cut & fix in position sawn Zigba wood formwork (yellow panels for slab side beams) to:-",
    item_no: "b",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764848,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "In Suspended floor beam",
    title: "CONCRETE WORK",
    sub_title:
      "Provide, cut & fix in position sawn Zigba wood formwork (yellow panels for slab side beams) to:-",
    item_no: "c",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764849,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "In Stair case",
    title: "CONCRETE WORK",
    sub_title:
      "Provide, cut & fix in position sawn Zigba wood formwork (yellow panels for slab side beams) to:-",
    item_no: "d",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764850,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "In Roof Slab",
    title: "CONCRETE WORK",
    sub_title:
      "Provide, cut & fix in position sawn Zigba wood formwork (yellow panels for slab side beams) to:-",
    item_no: "e",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764851,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "In Top Tie beam",
    title: "CONCRETE WORK",
    sub_title:
      "Provide, cut & fix in position sawn Zigba wood formwork (yellow panels for slab side beams) to:-",
    item_no: "f",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764852,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Ø 8 mm. deformed bar",
    title: "CONCRETE WORK",
    sub_title:
      "Steel reinforcement for use in super structure concrete works with a minimum yield strength fyk of 400MPa. Reinforcement shall be according to Structural Drawings and Technical Specifications. Price includes cutting bending, placing in position and tying wires.",
    item_no: "a",
    unit: "KG",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764853,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Ø 10 mm. deformed bar",
    title: "CONCRETE WORK",
    sub_title:
      "Steel reinforcement for use in super structure concrete works with a minimum yield strength fyk of 400MPa. Reinforcement shall be according to Structural Drawings and Technical Specifications. Price includes cutting bending, placing in position and tying wires.",
    item_no: "b",
    unit: "KG",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764854,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Ø 12 mm. deformed bar",
    title: "CONCRETE WORK",
    sub_title:
      "Steel reinforcement for use in super structure concrete works with a minimum yield strength fyk of 400MPa. Reinforcement shall be according to Structural Drawings and Technical Specifications. Price includes cutting bending, placing in position and tying wires.",
    item_no: "c",
    unit: "KG",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764855,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Ø 14 mm. deformed bar",
    title: "CONCRETE WORK",
    sub_title:
      "Steel reinforcement for use in super structure concrete works with a minimum yield strength fyk of 400MPa. Reinforcement shall be according to Structural Drawings and Technical Specifications. Price includes cutting bending, placing in position and tying wires.",
    item_no: "d",
    unit: "KG",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764856,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Ø 16 mm. deformed bar",
    title: "CONCRETE WORK",
    sub_title:
      "Steel reinforcement for use in super structure concrete works with a minimum yield strength fyk of 400MPa. Reinforcement shall be according to Structural Drawings and Technical Specifications. Price includes cutting bending, placing in position and tying wires.",
    item_no: "e",
    unit: "KG",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764857,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Ø 20 mm. deformed bar",
    title: "CONCRETE WORK",
    sub_title:
      "Steel reinforcement for use in super structure concrete works with a minimum yield strength fyk of 400MPa. Reinforcement shall be according to Structural Drawings and Technical Specifications. Price includes cutting bending, placing in position and tying wires.",
    item_no: "f",
    unit: "KG",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764858,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "20cm thick hollow concrete block wall bedded in cement sand mortar 1:3 both sides left for plastering.",
    title: "BLOCK WORK",
    sub_title: null,
    item_no: 2.1,
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764859,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Ditto as item 2.1, but 15cm thick hollow concrete block.",
    title: "BLOCK WORK",
    sub_title: null,
    item_no: 2.2,
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764860,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "D1 Size 120 x 265 cm",
    title: "CARPENTARY AND JOINERY WORK",
    sub_title:
      "Wooden Doors 40 mm thick semi solid core doors made from painted MDF,solid timber frame and painted for internal use. Price shall include wood framing, best quality cylindrical lock, kicking plate, hinges, three coats of varnish paint, door stopper & all necessary accessories to complete the work as per details and specifications given by the architect.",
    item_no: "a",
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764861,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "D2 Size 100x 210 cm",
    title: "CARPENTARY AND JOINERY WORK",
    sub_title:
      "Wooden Doors 40 mm thick semi solid core doors made from painted MDF,solid timber frame and painted for internal use. Price shall include wood framing, best quality cylindrical lock, kicking plate, hinges, three coats of varnish paint, door stopper & all necessary accessories to complete the work as per details and specifications given by the architect.",
    item_no: "b",
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764862,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "D3 Size 80X210cm",
    title: "CARPENTARY AND JOINERY WORK",
    sub_title:
      "Wooden Doors 40 mm thick semi solid core doors made from painted MDF,solid timber frame and painted for internal use. Price shall include wood framing, best quality cylindrical lock, kicking plate, hinges, three coats of varnish paint, door stopper & all necessary accessories to complete the work as per details and specifications given by the architect.",
    item_no: "c",
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764863,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "D4 Size 75X210cm",
    title: "CARPENTARY AND JOINERY WORK",
    sub_title:
      "Wooden Doors 40 mm thick semi solid core doors made from painted MDF,solid timber frame and painted for internal use. Price shall include wood framing, best quality cylindrical lock, kicking plate, hinges, three coats of varnish paint, door stopper & all necessary accessories to complete the work as per details and specifications given by the architect.",
    item_no: "D",
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764864,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Upper and lower chord, diameter 120mm",
    title: "CARPENTARY AND JOINERY WORK",
    sub_title:
      "Truss Members - All structural timber shall be well seasoned eucalyptus and shall be painted two coats of anti- termite solution. Each truss shall be firmly fixed to concrete tie beams with diameter 6mm reinforcement bars.",
    item_no: "a",
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764865,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Vertical and diagonal members diameter 100mm",
    title: "CARPENTARY AND JOINERY WORK",
    sub_title:
      "Truss Members - All structural timber shall be well seasoned eucalyptus and shall be painted two coats of anti- termite solution. Each truss shall be firmly fixed to concrete tie beams with diameter 6mm reinforcement bars.",
    item_no: "b",
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764866,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Zigba purling 50x70mm placed at c/c 900mm",
    title: "CARPENTARY AND JOINERY WORK",
    sub_title:
      "Truss Members - All structural timber shall be well seasoned eucalyptus and shall be painted two coats of anti- termite solution. Each truss shall be firmly fixed to concrete tie beams with diameter 6mm reinforcement bars.",
    item_no: "c",
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764867,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "860 mm development length gutter",
    title: "ROOFING",
    sub_title: null,
    item_no: 4.2,
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764868,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Ditto but 300 mm development length flashing",
    title: "ROOFING",
    sub_title: null,
    item_no: 4.3,
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764869,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "D-1 Size: 100mmx2650mm",
    title: "ALUMINIUM WORKS",
    sub_title:
      "Supply and fix doors shall be made from aluminum tubular profile frames, 2mm thick average weight 1000gm/ml, partly covered with HPL sheet according to the detail drawing and window door schedule. Price shall includes best quality iron monger, ASSA or equivalent type of cylindrical lock, 6mm thick clear glass with all necessary accessories.",
    item_no: "5.1",
    unit: "NO.",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764870,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "SD-1 Size: 3000mmx2650mm",
    title: "ALUMINIUM WORKS",
    sub_title:
      "Supply and fix Sliding-doors shall be made from aluminum tubular profile frames, 2mm thick average weight 1000gm/ml, according to the detail drawing and window door schedule. Price shall includes best quality iron monger, ASSA or equivalent type of cylindrical lock, 6mm thick clear glass with all necessary accessories.",
    item_no: 5.2,
    unit: "NO.",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764871,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "W-1 Size: 1700mmx1700mm",
    title: "ALUMINIUM WORKS",
    sub_title:
      "Supply and fix Windows shall be made from aluminum tubular profile frames, 2mm thick average weight 1000gm/ml, according to the detail drawing and window door schedule. Price shall includes best quality window lock and 6mm thick clear glass with all necessary accessories.",
    item_no: "a",
    unit: "NO.",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764872,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "W-2 Size: 1500mmx4150mm",
    title: "ALUMINIUM WORKS",
    sub_title:
      "Supply and fix Windows shall be made from aluminum tubular profile frames, 2mm thick average weight 1000gm/ml, according to the detail drawing and window door schedule. Price shall includes best quality window lock and 6mm thick clear glass with all necessary accessories.",
    item_no: "b",
    unit: "NO.",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764873,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "W-3 Size: 750mmx1000mm",
    title: "ALUMINIUM WORKS",
    sub_title:
      "Supply and fix Windows shall be made from aluminum tubular profile frames, 2mm thick average weight 1000gm/ml, according to the detail drawing and window door schedule. Price shall includes best quality window lock and 6mm thick clear glass with all necessary accessories.",
    item_no: "c",
    unit: "NO.",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764874,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "W-4 Size: 2060mmx2000mm",
    title: "ALUMINIUM WORKS",
    sub_title:
      "Supply and fix Windows shall be made from aluminum tubular profile frames, 2mm thick average weight 1000gm/ml, according to the detail drawing and window door schedule. Price shall includes best quality window lock and 6mm thick clear glass with all necessary accessories.",
    item_no: "d",
    unit: "NO.",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764875,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Supply and fix 6mm blue tinted structural glass curtain wall, in compliance with : Preload the test specimen (ASTM E 330), The test for air leakage (ASTM E283),The test for static water penetration (ASTM E331) ,  The test for water penetration under dynamic air pressure (AAMA 501.1), Understory displacement test shall be performed per AAMA 501.4,The test for structural performance (ASTM E330). Wall mountings types;. Single Arm Wall/Fin Fitting ,Left Hand Single Arm Wall/Fin Fitting , Right Hand Single Arm Wall/Fin Fitting, Double Arm Wall/Fin Fitting . All glass was fully tempered glass conforming to the specifications of ANSI Z97.1, ASTM C 1048-97b and CPSC 16 CFR 1201.",
    title: "ALUMINIUM WORKS",
    sub_title:
      "Supply and fix Windows shall be made from aluminum tubular profile frames, 2mm thick average weight 1000gm/ml, according to the detail drawing and window door schedule. Price shall includes best quality window lock and 6mm thick clear glass with all necessary accessories.",
    item_no: 5.5,
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764876,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Diameter 50mm, 2mm thick aluminum hand rail and diameter 40mmx2mm thick aluminum post anchored to concrete steps place c/c 900mm and including diameter  20mmx1.6mm thick aluminum bottom rails in three rows. Price shall include all the necessary accessories and according to detail drawing and Engineer approval.",
    title: "ALUMINIUM WORKS",
    sub_title:
      "Supply and fix Windows shall be made from aluminum tubular profile frames, 2mm thick average weight 1000gm/ml, according to the detail drawing and window door schedule. Price shall includes best quality window lock and 6mm thick clear glass with all necessary accessories.",
    item_no: "5.6",
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764877,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Ditto as item No. 4.8 but for guard rail",
    title: "ALUMINIUM WORKS",
    sub_title:
      "Supply and fix Windows shall be made from aluminum tubular profile frames, 2mm thick average weight 1000gm/ml, according to the detail drawing and window door schedule. Price shall includes best quality window lock and 6mm thick clear glass with all necessary accessories.",
    item_no: "5.7",
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764878,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "To Internal Wall Surfaces",
    title: "FINISHING WORKS",
    sub_title:
      "Supply, prepare and apply two coats of Portland cement plaster  in accordance with the technical specifications. Price shall include pre-cleaning and preparation of the surface.",
    item_no: "a",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764879,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "To concrete ceiling surface",
    title: "FINISHING WORKS",
    sub_title:
      "Supply, prepare and apply two coats of Portland cement plaster  in accordance with the technical specifications. Price shall include pre-cleaning and preparation of the surface.",
    item_no: "b",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764880,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "To stair case",
    title: "FINISHING WORKS",
    sub_title:
      "Supply, prepare and apply two coats of Portland cement plaster  in accordance with the technical specifications. Price shall include pre-cleaning and preparation of the surface.",
    item_no: "c",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764881,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "To external Wall Surfaces",
    title: "FINISHING WORKS",
    sub_title:
      "Supply, prepare and apply two coats of Portland cement plaster  in accordance with the technical specifications. Price shall include pre-cleaning and preparation of the surface.",
    item_no: "d",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764882,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "To Internal Wall Surfaces",
    title: "FINISHING WORKS",
    sub_title:
      "Supply, prepare and apply gypsum plaster  in accordance with the technical specifications. Price shall include pre-cleaning and preparation of the surface.",
    item_no: "a",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764883,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "To concrete ceiling surface",
    title: "FINISHING WORKS",
    sub_title:
      "Supply, prepare and apply gypsum plaster  in accordance with the technical specifications. Price shall include pre-cleaning and preparation of the surface.",
    item_no: "b",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764884,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "To stair case",
    title: "FINISHING WORKS",
    sub_title:
      "Supply, prepare and apply gypsum plaster  in accordance with the technical specifications. Price shall include pre-cleaning and preparation of the surface.",
    item_no: "c",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764885,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "To external Wall Surfaces",
    title: "FINISHING WORKS",
    sub_title:
      "Supply, prepare and apply gypsum plaster  in accordance with the technical specifications. Price shall include pre-cleaning and preparation of the surface.",
    item_no: "d",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764886,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Supply and fix 8mm thick porcelain floor finish Quality of floor finish to be approved by the Engineer. Price shall include ratio 1:3 cement sand mortar bed and cement grouting.",
    title: "FINISHING WORKS",
    sub_title: "Floor finish",
    item_no: "a",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764887,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Supply and fix 8mm thick ceramic floor finish Quality of floor finish to be approved by the Engineer. Price shall include ratio 1:3 cement sand mortar bed and cement grouting.",
    title: "FINISHING WORKS",
    sub_title: "Floor finish",
    item_no: "b",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764888,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Supply and fix wooden parquet floor finish with 20mm thick and 70mm width tongued and grooved boards on to 60mm x 100mm sawn timber joists spaced 500mm apart at right angles to the direction of the boards. The joists should be accurately laid and embedded in concrete until the clearance between the top of concrete and joists shall be 20mm. Price shall include 10cm high skirting.",
    title: "FINISHING WORKS",
    sub_title: "Floor finish",
    item_no: "d",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764889,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "10cm high with 8mm thick porcelain skirting",
    title: "FINISHING WORKS",
    sub_title:
      "Supply and fix skirting as per Engineer approval. Price shall include 1:3 cement sand mortar bed and cement grouting.",
    item_no: "a",
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764890,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "10cm high with 10cm thick Wooden parquet skirting",
    title: "FINISHING WORKS",
    sub_title:
      "Supply and fix skirting as per Engineer approval. Price shall include 1:3 cement sand mortar bed and cement grouting.",
    item_no: "b",
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764891,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Supply and fix 6mm thick ceramic wall tile in toilets with the specification and drawing.",
    title: "FINISHING WORKS",
    sub_title: "",
    item_no: 6.6,
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764892,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "3 x 30cm thick granite stair tread.",
    title: "FINISHING WORKS",
    sub_title:
      "Supply and fix granite for stair thread, stair riser, stair landing and Stair skirting as per drawing. Price shall include 1:3 ratio cement sand mortar bed and cement grouting.",
    item_no: "a",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764893,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "2x17cm thick granite stair riser.",
    title: "FINISHING WORKS",
    sub_title:
      "Supply and fix granite for stair thread, stair riser, stair landing and Stair skirting as per drawing. Price shall include 1:3 ratio cement sand mortar bed and cement grouting.",
    item_no: "b",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764894,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "3cm thick granite flooring for stair landing.",
    title: "FINISHING WORKS",
    sub_title:
      "Supply and fix granite for stair thread, stair riser, stair landing and Stair skirting as per drawing. Price shall include 1:3 ratio cement sand mortar bed and cement grouting.",
    item_no: "c",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764895,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Supply and fix granite for stair thread, stair riser, stair landing and Stair skirting as per drawing. Price shall include 1:3 ratio cement sand mortar bed and cement grouting.",
    title: "FINISHING WORKS",
    sub_title:
      "Supply and fix granite for stair thread, stair riser, stair landing and Stair skirting as per drawing. Price shall include 1:3 ratio cement sand mortar bed and cement grouting.",
    item_no: "d",
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764896,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "3 x 28cm thick marble window sill.",
    title: "FINISHING WORKS",
    sub_title:
      "Supply and fix  marble for window sill, copping and threshold as per drawing. Price shall include 1:3 ratio cement sand mortar bed and cement grouting.",
    item_no: "a",
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764897,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "3 x 28cm thick marble copping",
    title: "FINISHING WORKS",
    sub_title:
      "Supply and fix  marble for window sill, copping and threshold as per drawing. Price shall include 1:3 ratio cement sand mortar bed and cement grouting.",
    item_no: "b",
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764898,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "3 x 28cm thick marble threshold",
    title: "FINISHING WORKS",
    sub_title:
      "Supply and fix  marble for window sill, copping and threshold as per drawing. Price shall include 1:3 ratio cement sand mortar bed and cement grouting.",
    item_no: "c",
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764899,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Supply and fix Gypsum board ceiling suspended on concrete soffit .",
    title: "FINISHING WORKS",
    sub_title: "Floor finish",
    item_no: "6.9",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764900,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Supply and apply average 70mm thick light weight concrete in mix 1:2:5 cement, pumice and sand laid over RC roof slab with proper slope towards down pipe and corners angled are 450 at parapet and roof slab connection as shown on the detail drawing.",
    title: "FINISHING WORKS",
    sub_title: "Floor finish",
    item_no: "6.10",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764901,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Supply & apply 4mm thick membrane water proof material. All Material shall be approved by the Engineer.",
    title: "FINISHING WORKS",
    sub_title: "Floor finish",
    item_no: "6.11",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764902,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Supply and fix 30x30x3mm angle iron corner protection up to a height of 150cm from floor finish level, flushed to walls.",
    title: "FINISHING WORKS",
    sub_title: "Floor finish",
    item_no: "6.12",
    unit: "NO.",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764903,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "To Internal Wall Surfaces",
    title: "PAINTING",
    sub_title:
      "Supply and Apply three coats of plastic emulsion paint to all plastered and finished wall surface the choice of color and patterns of painting shall be approved by the supervisor .",
    item_no: "a",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764904,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "To Gypsum ceiling",
    title: "PAINTING",
    sub_title:
      "Supply and Apply three coats of plastic emulsion paint to all plastered and finished wall surface the choice of color and patterns of painting shall be approved by the supervisor .",
    item_no: "b",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764905,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "To Chip wood ceiling",
    title: "PAINTING",
    sub_title:
      "Supply and Apply three coats of plastic emulsion paint to all plastered and finished wall surface the choice of color and patterns of painting shall be approved by the supervisor .",
    item_no: "c",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764906,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "To stair soffit",
    title: "PAINTING",
    sub_title:
      "Supply and Apply three coats of plastic emulsion paint to all plastered and finished wall surface the choice of color and patterns of painting shall be approved by the supervisor .",
    item_no: "d",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764907,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "To External wall surface",
    title: "PAINTING",
    sub_title:
      "Supply and Apply three coats of plastic emulsion paint to all plastered and finished wall surface the choice of color and patterns of painting shall be approved by the supervisor .",
    item_no: "e",
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764908,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "With copper bus bar of 63A and 25 % reserve space",
    title: "ELECTRICAL INSTALLATION",
    sub_title:
      "Flush mounted main distribution board MDB with lockable door, earthling lead cable terminal, connectors and all the necessary accessories  consisting of:- 1pc main MCB of 50A, 1-ph Icu = 6KA 1pc MCB of 20A,1-ph Icu =6KA 2pcs MCB of 25A,1-ph Icu =6KA 8pcs MCB of 16A,1-ph Icu =6KA 3pcs MCB of 16A,1-ph Icu = 6KA ",
    item_no: "a",
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764909,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Flush mounted main distribution board SDB-1F with lockable door, earthing lead cable terminal, with lockable door, earthling lead cable terminal, connectors and all the necessary accessories  consisting of:- 1pc main MCB of 50A, 1-ph Icu = 6KA 1pc MCB of 20A,1-ph Icu =6KA 2pcs MCB of 25A,1-ph Icu =6KA 8pcs MCB of 16A,1-ph Icu =6KA 3pcs MCB of 16A,1-ph Icu = 6KA With copper bus bar of 63A and 25 % reserve space",
    title: "ELECTRICAL INSTALLATION",
    sub_title: null,
    item_no: "8.2",
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764910,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Flush mounted main distribution board SDB-2F with lockable door, earthing lead cable terminal, with lockable door, earthling lead cable terminal, connectors and all the necessary accessories  consisting of:-1pc main MCB of 25A, 1-ph  Icu = 6KA  6pcs MCB of 16A,1-ph Icu =6KA  2pcs MCB of 10A, 1-ph Icu = 6KA With copper bus bar of 63A and 25 % reserve space",
    title: "ELECTRICAL INSTALLATION",
    sub_title: null,
    item_no: "8.3",
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764911,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Light points in thermoplastic conduit of 16mm fed by PVC conductor of 2x2.5sq.mm color coded and labeled",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "Light Point",
    item_no: 8.4,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764912,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Single pole",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "Switch",
    item_no: 8.5,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764913,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Double pole",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "Switch",
    item_no: 8.6,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764914,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Two way switch",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "Switch",
    item_no: 8.7,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764915,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "16 A /230 V 2p+e Socket outlet in conduit of dia. 16mm  fed by PVC conductor of  3x2.5sq.mm color coded",
    title: "ELECTRICAL INSTALLATION",
    sub_title: null,
    item_no: "8.8",
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764916,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Ditto but for stove 20A, 1ph fed by 3x4sq.mm in  dia. 19mm and on/off switch",
    title: "ELECTRICAL INSTALLATION",
    sub_title: null,
    item_no: "8.9",
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764917,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Ditto but for injera metad 25A, 1ph fed by 3x6sq.mm in dia. 19mm and on/off switch",
    title: "ELECTRICAL INSTALLATION",
    sub_title: null,
    item_no: 8.1,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764918,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "16 A",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "Extra over 16A for flush mounting with detachable frames",
    item_no: 8.11,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764919,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "16 A Twin",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "Extra over 16A for flush mounting with detachable frames",
    item_no: 8.12,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764920,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "20A, 1ph with on-off switch",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "Extra over 16A for flush mounting with detachable frames",
    item_no: 8.13,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764921,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "25A for injera metad, 1ph with on-off switch",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "Extra over 16A for flush mounting with detachable frames",
    item_no: 8.14,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764922,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Massive 3625/81/43+5x40 INC",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "Ditto but for injera metad 25A, 1ph fed by 3x6sq.mm in",
    item_no: 8.15,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764923,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "LED spot light+GU10 5W LED",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "Ditto but for injera metad 25A, 1ph fed by 3x6sq.mm in",
    item_no: 8.16,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764924,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "RZB 901399.002+ 7.5W LED",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "Ditto but for injera metad 25A, 1ph fed by 3x6sq.mm in",
    item_no: 8.17,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764925,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "RZB 581609.002+ 8.7W LED",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "Ditto but for injera metad 25A, 1ph fed by 3x6sq.mm in",
    item_no: 8.18,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764926,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "RZB 401000.002+ 2x4W LED",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "Ditto but for injera metad 25A, 1ph fed by 3x6sq.mm in",
    item_no: 8.19,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764927,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Massive 8176902/01/09+40W INC",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "Ditto but for injera metad 25A, 1ph fed by 3x6sq.mm in",
    item_no: 8.2,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764928,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Modus PL22+42W LED",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "Ditto but for injera metad 25A, 1ph fed by 3x6sq.mm in",
    item_no: 8.21,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764929,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Disano Faro 1234 wall",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "Ditto but for injera metad 25A, 1ph fed by 3x6sq.mm in",
    item_no: 8.22,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764930,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "flush mounting up to roof with TV outlet",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "TV points  in thermoplastic conduit",
    item_no: null,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764931,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Master antenna TV system for entertainment purpose with broad band AM/FM antenna and 2 dish( for Arab sat and DSTV)with higher capacity available on Market, antenna mast,Preamplifiers,line,head end and distribution amplifiers,UHF/VHF converters,modulators,filiters,attenuators splitter/tapoff/ mixer with complete analysis made on signal level,cable,splitter,insertion,isolation losses and signal level in dB at outeach lets,with latest technologies,coupler for satellite and terrestrial TV network,recent technology decoders,encoders for four flats sand all the necessary accessories.",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "TV points  in thermoplastic conduit",
    item_no: 8.24,
    unit: "LS",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764932,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "8 contact points in thermoplastic conduit of 13mm with standard 4pair CAT 6 UTP telephone  cables with junction boxes as ETC standard and regulations and  as per experts requirement with personnel having a license from ETC. Shop drawings with complete analysis to be submitted prior to purchase and installation",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "TV points  in thermoplastic conduit",
    item_no: 8.3,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764933,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Single  module (RJ 45 CAT 5e) ,8 contact out lets  for flush mounting with labeling Telephone terminal Blocks (punch downs) with corresponding box and frame",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "TV points  in thermoplastic conduit",
    item_no: 8.31,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764934,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Surface mounted main distribution frame made of steel  20 pairs telephone terminal blocks or punch down blocks with lockable doors wall support structure complete accessories or equivalent pair as ETC standard",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "TV points  in thermoplastic conduit",
    item_no: 8.32,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764935,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "3x6 sq.mm",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "TV points  in thermoplastic conduit",
    item_no: 8.33,
    unit: "M",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764936,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "3x10 sq.mm  (Tentative)",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "TV points  in thermoplastic conduit",
    item_no: 8.34,
    unit: "M",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764937,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "50 x 50 x50 cm",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "TV points  in thermoplastic conduit",
    item_no: 8.35,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764938,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Diameter 32 mm",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "TV points  in thermoplastic conduit",
    item_no: 8.36,
    unit: "M",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764939,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Diameter 50mm",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "TV points  in thermoplastic conduit",
    item_no: 8.37,
    unit: "M",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764940,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "50 x 50 x 50 cm  inspection pit",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "TV points  in thermoplastic conduit",
    item_no: 8.38,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764941,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Diameter 16mm and 240cm long copper rod",
    title: "ELECTRICAL INSTALLATION",
    sub_title: "TV points  in thermoplastic conduit",
    item_no: 8.4,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764942,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Supply, install, test and commission Bath Tub made of  white Standards.vitreous China complete with lever  controlled   Remer or equivalent chrome plated lever   shower head, plug, chrome plated chain, P-smell trap and  fittings and accessories for the proper installation and operation  all the necessary connecting and fixing of the tub. The tub  shall conform with Local and International  Size: 1800*70mm (L*W) (Approximate Size). Color: White",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.1,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764943,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Hand Wash Basin Supply and fix Hand Wash Basin , made of white vitreous China (BS3402)  ,with pedestal. The fixture shall conform to BS5506-3 or equivalent institution. Size  500 x 405 mm. The waste fittings, shall be stainless steel bottle trap connecting pieces, fixing and supporting  element and all other  accessories which complete the set. shall comply with  BS standard or equivalent institution. The tap ware shall be brass and comply to BS2878:1980 with approved angle valve and all necessary accessories",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.2,
    unit: "Nº",
    quantity: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764944,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Water Closet Supply and fix water closet, of wash down action Supply and fix water closet, of wash down action, made from white vitreous China, which comply  with requirement of  BS standard or equivalent institution. The waste fittings connecting pieces,  fixing and supporting element and other  accessories which complete the set shall comply with the relevant clauses of BS standard or  equivalent institution.",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.3,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764945,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Electric Water Heater Supply and fix 50 litre internally glass ligned storage type electric water  heater of  approved quality  complete with all the necessary accessories.",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.4,
    unit: "NO.",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764946,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Kitchen Sink Supply and fix stainless steel Sink ,double bowel, complete with trap, drain connection, drainage and over flow, heavy duty  mixing faucet, plug, chain, etc. and all other necessary accessories. Size:- 1200 x 500 x150mm (bowl depth)",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.5,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764947,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Floor Drain Supply and fix Ф50mm  enameled cast Iron Floor  Drain ,conform to ASME Standards ,A112.6.3 (Light Duty)or equivalent institution complete with P-smell trap and  all the necessary  accessories.",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.6,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764948,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Toilet Paper Holder Supply and  fix  toilet paper holder, of approved  quality, made from white vitrous china, complete with all the necessary  accessories.",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.7,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764949,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Soap Holder   Supply and fix soap holder of approved  quality, made from white vitreous china,  complete with all the necessary accessories.",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.8,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764950,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Crystal Glass Mirror  Supply and fix crystal  glass mirror  splash  backs, with copper back  protected. size 500mm x 400mm Complete with all  the necessary accessories.",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.1,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764951,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Cold Water Supply pipe  Supply, lay and connect Aluminum pressure pipe inner pipe made of silane-interlanced polyethylene and outer part with protective jacket made of HDPE. Operating temperature range 0-95°c for hot and cold  drinking water. Operating pressure 10 bar(PN10), for cold water supply system to sanitary fixtures Complete with all  the necessary connecting pieces such as bends, Ys, Ts,  reducers, nipples, unions, galvanized clips, the interval shall be as per manufacturer's   recommendation & supports(if any) etc... Unit price  shall include ,disinfection of the pipes with Chlorine and all  the necessary assistance to the installation works . The installation shall be tested at a pressure of  10kg/cm².The Pipes and fittings shall conform to BS3505/DIN8062 or equivalent institution. Outer  Diameter 20mm,min wall thickness  2.50mm",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.2,
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764952,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Ditto Item No 11 but outer diameter 25mm",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: "9.2a",
    unit: "ML",
    quantity: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764953,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Minimum wall thickness 3.0mm",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: "9.3b",
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764954,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Ditto Item No 11 but outer diameter 32mm Minimum wall thickness 3.50mm",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.3,
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764955,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Ditto Item No 11 but outer diameter 40mm Minimum wall thickness 3.50mm",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.4,
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764956,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Angle Valve Supply and fix chrome plated service (angle)valves  ,of approved standard,  before Hand wash basin, water closets,  janitery sink  and other fixtures  complete with unions, elastic water proofing ,hand  wheels of normal quality and with all other necessary accessories. The angle valve internal diameter shall  be compatible with PP-R pipes. Outer diameter = 20 mm",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.5,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764957,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Gate Valve Supply and fix bronze  gate valves (PN 16 ), outer diameter 20mm , of approved standards,  on internal branch water pipes, and water tank  where shown on the drawing  complete with all the necessary accessories .",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.6,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764958,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Ditto Item No 16 but, 25mm outer diameter,",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.6,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764959,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "One way Valve Supply and fix bronze one-way valves (PN 16 ) ,  of approved standards compatible with PPR  pipe, for delivery pipes of the water tank complete with all  the necessary accessories. Diameter 20mm",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.7,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764960,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Diameter 20mm",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: null,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764961,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "Diameter 40mm",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: "9.7b",
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764962,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Waste Water Drainage Pipe Supply and lay 50mm(2'') diameter uPVC pipes minimum wall thickness 2.0mm for foul  water collection, vent system and down spout. The pipes shall be supported with  galvanized   clips screwed to slab, beam columns ... etc at  every joints, bends and at 0.5meters interval in    straight line. All exposed pipes shall be painted with UV reflective oil paint, similar to the walls, slabs, beams…etc it is fixed on  & complete with  all necessary fittings and clean out. The pipes, accessories, fittings & method of welding comply  to BS 5255 or Equivalent Institution. Unit price shall include all the necessary assistance to the installation works.",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.6,
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764963,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Down pipe for roof drainage Supply and fix Diameter 110mm uPVC Downpipes  min. wall thickness3.2mm, with mass concrete support inlet, galvanized clips at every elbows, joints and at every  1m interval complete with all accessories. The pipes,  accessories, fittings & method of welding shall comply  with the requirement of BS 4514or equivalent Institution.  Unit price shall include all the necessary assistances to the installation works.",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 9.8,
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764964,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Storm water drainage ditch Construct ditch out of masonry stone wall & base of thickness 40 cm laid on 150mm  thick  well compacted selected material as shown  on the detail drawing for ditches designated  on the site plan. Internal size :- 30cm wide & 30 cm avg depth",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 24,
    unit: "ML",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764965,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Manhole Construct rectangular  manhole out of 100mm thick cast insitu cement concrete, internal dimension  600mmx600mm and 600mm (average depth), and all in  accordance  with  the given  detail drawings.   During construction the concrete shall be properly  vibrated and compacted. Unit  price  shall  include excavation  of  the  pit  to a depth of 750mm (max ), cart away of  the excavated  soil and formwork. All as shown on the detail drawing.",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 25,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764966,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Roof Mounted Water Tank Supply , and connect 3m3 capacity roto or equivalent  water tank.  Complete with all the  necessary accessories and connections such as inlet pipes,  outlet pipes, drain pipes, gate valves, over flow pipes , vent pipes with mesh cover , vent caps, manhole, etc,  all according  to the detail drawing . diameter 75mm  outlet pipe,  diameter 50mm inlet pipe,  diameter 50mm approved quality float valve diameter 50mm drainage pipe with horizontal bronze  gate valve( 16 BAR ) diameter 40mm over flow pipe  diameter 60mm inspection cover",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 26,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764967,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name:
      "Septic Tank Construct Septic tank of Volume 6m3 as per the detail  drawing , price includes Excavation, cart away, rebar, formwork and other necessary civil works including  collection tank and related facilities",
    title: "SANITARY   INSTALLATION",
    sub_title: null,
    item_no: 27,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764968,
  },
];

export const default_building_boq: any = [
  {
    super_title: "SUB STRUCTURE",
    task_name: "",
    title: "Title",
    sub_title: null,
    item_no: null,
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764809,
  },
  {
    super_title: "SUPER STRUCTURE",
    task_name: "",
    title: "Title",
    sub_title: null,
    item_no: null,
    unit: "M²",
    quantity: 0,
    unit_price: 0,
    total: 0,
    sheet_name: "sheet 1",
    key: 1617221764784,
  },
];
