export const init_road_boq: any = [
  {
    super_title:
      "Group I: Survey, Investigation and Design as per Employer's Requirement",
    task_name: "Route Selection Report",
    title: "Surveying",
    sub_title: null,
    item_no: "1.1.1",
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 1,
  },
  {
    super_title:
      "Group I: Survey, Investigation and Design as per Employer's Requirement",
    task_name: "Topographic Surveying Report",
    title: "Surveying",
    sub_title: null,
    item_no: "1.1.2",
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 2,
  },
  {
    super_title:
      "Group I: Survey, Investigation and Design as per Employer's Requirement",
    task_name: "Material and Geo-Technical Investigation Report",
    title: "Investigation",
    sub_title: null,
    item_no: "1.2.1",
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 3,
  },
  {
    super_title:
      "Group I: Survey, Investigation and Design as per Employer's Requirement",
    task_name: "Hydrology/Hydraulics Report",
    title: "Design",
    sub_title: null,
    item_no: "1.3.1",
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 4,
  },
  {
    super_title:
      "Group I: Survey, Investigation and Design as per Employer's Requirement",
    task_name: "Geometric Design Report",
    title: "Design",
    sub_title: null,
    item_no: "1.3.2",
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 5,
  },
  {
    super_title:
      "Group I: Survey, Investigation and Design as per Employer's Requirement",
    task_name: "Drainage and Bridge Design Report",
    title: "Design",
    sub_title: null,
    item_no: "1.3.3",
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 6,
  },
  {
    super_title:
      "Group I: Survey, Investigation and Design as per Employer's Requirement",
    task_name: "Pavement Design Report",
    title: "Design",
    sub_title: null,
    item_no: "1.3.4",
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 7,
  },
  {
    super_title:
      "Group I: Survey, Investigation and Design as per Employer's Requirement",
    task_name: "Ancillary",
    title: "Design",
    sub_title: null,
    item_no: "1.3.5",
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 8,
  },
  {
    super_title:
      "Group I: Survey, Investigation and Design as per Employer's Requirement",
    task_name: "Plan & Profile Working Drawing of Structures",
    title: "Design",
    sub_title: null,
    item_no: "1.3.6",
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 9,
  },
  {
    super_title:
      "Group I: Survey, Investigation and Design as per Employer's Requirement",
    task_name:
      "Construction Specification Package and Quality Assurance Manual",
    title: "Design",
    sub_title: null,
    item_no: "1.3.7",
    unit: "LS",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 10,
  },
  {
    super_title:
      "Group I: Survey, Investigation and Design as per Employer's Requirement",
    task_name:
      "20% retained as stated on Employer's Requirement and will be released after the earth work is completed",
    title: "Design",
    sub_title: null,
    item_no: "1.3.8",
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 11,
  },
  {
    super_title:
      "Group II: Series 1000/Division 1400 Project/Employer's Representative facilities as per Employer's Requirement",
    task_name: "Provision of Temporary Facilities to the Engineer and Staff",
    title: null,
    sub_title: null,
    item_no: 2.1,
    unit: "LS",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 12,
  },
  {
    super_title:
      "Group II: Series 1000/Division 1400 Project/Employer's Representative facilities as per Employer's Requirement",
    task_name: "Office Building Completed as Specified",
    title: null,
    sub_title: null,
    item_no: 2.2,
    unit: "LS",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 13,
  },
  {
    super_title:
      "Group II: Series 1000/Division 1400 Project/Employer's Representative facilities as per Employer's Requirement",
    task_name: "Office Furniture and Equipment",
    title: null,
    sub_title: null,
    item_no: 2.3,
    unit: "LS",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 14,
  },
  {
    super_title:
      "Group II: Series 1000/Division 1400 Project/Employer's Representative facilities as per Employer's Requirement",
    task_name: "Laboratory Building Completed as Specified",
    title: null,
    sub_title: null,
    item_no: 2.4,
    unit: "LS",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 15,
  },
  {
    super_title:
      "Group II: Series 1000/Division 1400 Project/Employer's Representative facilities as per Employer's Requirement",
    task_name: "Laboratory Furniture and Equipment",
    title: null,
    sub_title: null,
    item_no: 2.5,
    unit: "LS",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 16,
  },
  {
    super_title:
      "Group II: Series 1000/Division 1400 Project/Employer's Representative facilities as per Employer's Requirement",
    task_name:
      "Maintenance and Service for Office and Laboratory including Assistants and D.L",
    title: null,
    sub_title: null,
    item_no: 2.6,
    unit: "MONTH",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 17,
  },
  {
    super_title:
      "Group II: Series 1000/Division 1400 Project/Employer's Representative facilities as per Employer's Requirement",
    task_name: "Provision of Vehicle Type B for the Employers Representative",
    title: null,
    sub_title: null,
    item_no: 2.7,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 18,
  },
  {
    super_title:
      "Group II: Series 1000/Division 1400 Project/Employer's Representative facilities as per Employer's Requirement",
    task_name:
      "Fuel and Lubricants, Maintenance, Servicing Including Driver Type B Vehicle",
    title: null,
    sub_title: null,
    item_no: 2.8,
    unit: "MONTH",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 19,
  },
  {
    super_title:
      "Group II: Series 1000/Division 1400 Project/Employer's Representative facilities as per Employer's Requirement",
    task_name: "Provision of Surveying Equipment with all Accessories",
    title: "Survey Equipment",
    sub_title: null,
    item_no: "2.9.1",
    unit: "LS",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 20,
  },
  {
    super_title:
      "Group II: Series 1000/Division 1400 Project/Employer's Representative facilities as per Employer's Requirement",
    task_name:
      "Provision of Service and Maintenance Including Surveyor Assistants",
    title: "Survey Equipment",
    sub_title: null,
    item_no: "2.9.2",
    unit: "MONTH",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 21,
  },
  {
    super_title:
      "Group II: Series 1000/Division 1400 Project/Employer's Representative facilities as per Employer's Requirement",
    task_name: "Provide All Stationery and Mobile Radios",
    title: "Communication Radio",
    sub_title: null,
    item_no: "2.10.1",
    unit: "LS",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 22,
  },
  {
    super_title:
      "Group II: Series 1000/Division 1400 Project/Employer's Representative facilities as per Employer's Requirement",
    task_name: "Provision of Service and Maintenance",
    title: "Communication Radio",
    sub_title: null,
    item_no: "2.10.2",
    unit: "MONTH",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 23,
  },
  {
    super_title:
      "Group III: Series 1000/Division 1500/Detour and Traffic Management",
    task_name: "Traffic Management Plan and implementation",
    title: null,
    sub_title: null,
    item_no: 3.1,
    unit: "MONTH",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 24,
  },
  {
    super_title:
      "Group III: Series 1000/Division 1500/Detour and Traffic Management",
    task_name: "Detour Construction",
    title: null,
    sub_title: null,
    item_no: 3.2,
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 25,
  },
  {
    super_title:
      "Group III: Series 1000/Division 1500/Detour and Traffic Management",
    task_name: "Detour Maintenance",
    title: null,
    sub_title: null,
    item_no: 3.3,
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 26,
  },
  {
    super_title:
      "Group III: Series 1000/Division 1500/Detour and Traffic Management",
    task_name: "Sign Board at Project Start and End",
    title: null,
    sub_title: null,
    item_no: 3.4,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 27,
  },
  {
    super_title:
      "Group III: Series 1000/Division 1500/Detour and Traffic Management",
    task_name: "Right of Way Limit Markers",
    title: null,
    sub_title: null,
    item_no: 3.5,
    unit: "N0",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 28,
  },
  {
    super_title: "Group IV: Series 2000 and 4000/Site Clearance and Earthwork",
    task_name:
      "Site Clearing and Grubbing, including demolish and removal of existing structures",
    title: "Clearing and Grubbing",
    sub_title: null,
    item_no: "4.1.1",
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 29,
  },
  {
    super_title: "Group IV: Series 2000 and 4000/Site Clearance and Earthwork",
    task_name: "Road Bed Preparation and Replacement of unsuitable material",
    title: "Clearing and Grubbing",
    sub_title: null,
    item_no: "4.1.2",
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 30,
  },
  {
    super_title: "Group IV: Series 2000 and 4000/Site Clearance and Earthwork",
    task_name: "Cut and Borrow to Fill (Mixing, Placing and Compaction)",
    title: "Earth Work",
    sub_title: null,
    item_no: "4.3.1",
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 31,
  },
  {
    super_title: "Group IV: Series 2000 and 4000/Site Clearance and Earthwork",
    task_name: "Cut to Spoil Material (Cut to Waste)",
    title: "Earth Work",
    sub_title: null,
    item_no: "4.3.2",
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 32,
  },
  {
    super_title: "Group IV: Series 2000 and 4000/Site Clearance and Earthwork",
    task_name: "Hard Excavation",
    title: "Earth Work",
    sub_title: null,
    item_no: "4.3.3",
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 33,
  },
  {
    super_title: "Group IV: Series 2000 and 4000/Site Clearance and Earthwork",
    task_name: "Improved Subgrade or Capping Layer Construction",
    title: "Earth Work",
    sub_title: null,
    item_no: "4.3.4",
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 34,
  },
  {
    super_title: "Group V: Series 5000/Sub-base",
    task_name: "Sub Base Placing  and Finishing",
    title: "Sub-Base",
    sub_title: null,
    item_no: 5.1,
    unit: "M3",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 35,
  },
  {
    super_title: "Group V: Series 6000/Base Course",
    task_name: "Road Base Placing and Finishing",
    title: "Road Base",
    sub_title: null,
    item_no: 6.1,
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 36,
  },
  {
    super_title: "Group VII:Series 7000/Bituminous Surfaces, AC",
    task_name: "Prime Coat",
    title: null,
    sub_title: null,
    item_no: 7.1,
    unit: "M2",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 37,
  },
  {
    super_title: "Group VII:Series 7000/Bituminous Surfaces, AC",
    task_name: "Asphalt Concrete",
    title: null,
    sub_title: null,
    item_no: 7.2,
    unit: "M2",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 38,
  },
  {
    super_title: "Group VII:Series 7000/Bituminous Surfaces, AC",
    task_name: "SST",
    title: null,
    sub_title: null,
    item_no: 7.3,
    unit: "M2",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 39,
  },
  {
    super_title:
      "Group VIII: Series 3000, Series 8000 and Series 9000/ Bridge,Culvert,Drainage and Protection work",
    task_name: "Paved Ditch in rular section and maymekden kebele seat",
    title: "Bridge/Culvert/Drainage & Protection work",
    sub_title: null,
    item_no: 8.1,
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 40,
  },
  {
    super_title:
      "Group VIII: Series 3000, Series 8000 and Series 9000/ Bridge,Culvert,Drainage and Protection work",
    task_name:
      "Side drainage pipes, walk way tiles and concrete curbing in town section",
    title: "Bridge/Culvert/Drainage & Protection work",
    sub_title: null,
    item_no: 8.2,
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 41,
  },
  {
    super_title:
      "Group VIII: Series 3000, Series 8000 and Series 9000/ Bridge,Culvert,Drainage and Protection work",
    task_name: "Pipe Culvert Construction",
    title: "Bridge/Culvert/Drainage & Protection work",
    sub_title: null,
    item_no: 8.3,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 42,
  },
  {
    super_title:
      "Group VIII: Series 3000, Series 8000 and Series 9000/ Bridge,Culvert,Drainage and Protection work",
    task_name: "Box and Slab Culvert Construction",
    title: "Bridge/Culvert/Drainage & Protection work",
    sub_title: null,
    item_no: 8.4,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 43,
  },
  {
    super_title:
      "Group VIII: Series 3000, Series 8000 and Series 9000/ Bridge,Culvert,Drainage and Protection work",
    task_name: "Bridge Construction",
    title: "Bridge/Culvert/Drainage & Protection work",
    sub_title: null,
    item_no: 8.5,
    unit: "Nº",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 44,
  },
  {
    super_title:
      "Group VIII: Series 3000, Series 8000 and Series 9000/ Bridge,Culvert,Drainage and Protection work",
    task_name: "Protection Work (Gabion, Retaining walls etc.)",
    title: "Bridge/Culvert/Drainage & Protection work",
    sub_title: null,
    item_no: 8.6,
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 45,
  },
  {
    super_title:
      "Group IX: Series 9000,Series 1000 and Series 2000/Road Furniture, HIV and Environment Works",
    task_name: "Kilometer Post and Delineator",
    title: null,
    sub_title: null,
    item_no: 9.1,
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 46,
  },
  {
    super_title:
      "Group IX: Series 9000,Series 1000 and Series 2000/Road Furniture, HIV and Environment Works",
    task_name: "Guardrails",
    title: null,
    sub_title: null,
    item_no: 9.2,
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 47,
  },
  {
    super_title:
      "Group IX: Series 9000,Series 1000 and Series 2000/Road Furniture, HIV and Environment Works",
    task_name: "Traffic Sign",
    title: null,
    sub_title: null,
    item_no: 9.3,
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 48,
  },
  {
    super_title:
      "Group IX: Series 9000,Series 1000 and Series 2000/Road Furniture, HIV and Environment Works",
    task_name: "Road Marks",
    title: null,
    sub_title: null,
    item_no: 9.4,
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 49,
  },
  {
    super_title:
      "Group IX: Series 9000,Series 1000 and Series 2000/Road Furniture, HIV and Environment Works",
    task_name: "Environmental Works",
    title: null,
    sub_title: null,
    item_no: 9.5,
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 50,
  },
  {
    super_title:
      "Group IX: Series 9000,Series 1000 and Series 2000/Road Furniture, HIV and Environment Works",
    task_name: "Environmental Management Plan",
    title: null,
    sub_title: null,
    item_no: 9.6,
    unit: "L.s",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 51,
  },
  {
    super_title:
      "Group IX: Series 9000,Series 1000 and Series 2000/Road Furniture, HIV and Environment Works",
    task_name: "General STD and HIV/AIDS Alleviation Program",
    title: null,
    sub_title: null,
    item_no: 9.7,
    unit: "MONTH",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 52,
  },
  {
    super_title:
      "Group IX: Series 9000,Series 1000 and Series 2000/Road Furniture, HIV and Environment Works",
    task_name:
      "Preparation of KAP survey, an Action Plan, Monitoring plan for STD & HIV/AIDS alleviation measures for the project to the Engineer's approval",
    title: null,
    sub_title: null,
    item_no: 9.8,
    unit: "L.s",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 53,
  },
  {
    super_title:
      "Group IX: Series 9000,Series 1000 and Series 2000/Road Furniture, HIV and Environment Works",
    task_name: "Professional indemnity",
    title: "Insurance coverage",
    sub_title: null,
    item_no: "9.9.1",
    unit: "LS",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 54,
  },
  {
    super_title:
      "Group IX: Series 9000,Series 1000 and Series 2000/Road Furniture, HIV and Environment Works",
    task_name: "Vehicle, CPM",
    title: "Insurance coverage",
    sub_title: null,
    item_no: "9.9.2",
    unit: "Year",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 55,
  },
  {
    super_title:
      "Group IX: Series 9000,Series 1000 and Series 2000/Road Furniture, HIV and Environment Works",
    task_name: "Personnel injury and damage to property",
    title: "Insurance coverage",
    sub_title: null,
    item_no: "9.9.3",
    unit: "LS",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 56,
  },
  {
    super_title:
      "Group IX: Series 9000,Series 1000 and Series 2000/Road Furniture, HIV and Environment Works",
    task_name: "Workmen",
    title: "Insurance coverage",
    sub_title: null,
    item_no: "9.9.4",
    unit: "LS",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 57,
  },
  {
    super_title:
      "Group IX: Series 9000,Series 1000 and Series 2000/Road Furniture, HIV and Environment Works",
    task_name: "Provision of Ambulance",
    title: "Insurance coverage",
    sub_title: null,
    item_no: "9.10",
    unit: "LS",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 58,
  },
];

export const default_road_boq: any = [
  {
    super_title: "",
    task_name: "",
    title: "",
    sub_title: null,
    item_no: null,
    unit: "KM",
    quantity: 0,
    unit_price: 0,
    total: 0,
    key: 1617221764809,
  },
];
