/**
 * Routes
 */
export const RouteConstants = {
  CASHER:"/casher",
  KENO_GAME: "/keno-game",
  TICKETING: "/ticketing",
  KENO_REPORT: "/keno-report",
  KENO_BILLS: "/keno-bills",
  SCANNED: "/scanned",
  RESOURCE: "/resource",
  DRAWED_GAMES: "/drawed_games",
  /**
   * Dashboard
   */
  DASHBOARD: "/",
  DASHBOARDS: "/dashboard",
  PROJECTS: "/project",
  PROJECT_LIST: "/project/:type",
  REGISTER_PROJECT: "/register-project",
  PROJECT_TAB: "/project/:id/:header/:menu/:tab",
  PROJECT_MENU: "/project/:id/:header/:menu",
  PROJECT: "/project/:id/:header",
  USER: "/user-management/:tab",
  MATERIAL_APPROVAL: "/project/:project_id/material-approval/:id",

  SUMMARY: "/summary",
  REPORT: "/report",
  STATUS_BOARD: "/status-board",
  DOCUMENT: "/document",
  EQUIPMENT: "/fixed-asset",
  INVENTORY: "/inventory",
  HUMAN_RESOURCE_INDEX: "/hr/:id",
  HUMAN_RESOURCE: "/hr",
  PROCUREMENT: "/procurement",
  SUB_CONTRACT_LIST: "/sub-contract-list",
  REGISTER_SUB_CONTRACT: "/register-sub-contract",
  FINANCE: "/finance",
  TASK: "/task",
  LETTER: "/letter",
  LOGIN: "/login",
  PRE_CONTRACT: "/pre-contract",
  REGISTER_PRE_CONTRACT: "/register",
  PRE_CONTRACT_SUMMARY: "/pre-contract/summary",
  PAYMENT: "/payment",
  PAYMENT_SUMMARY: "/payment/:id/:tab",

  STANDARDS: "/standard",

  RESET: "/reset",
  GOOGLE_AUTH_FORM: "/google-auth/:userId",
  EMAIL_CONFIRMATION: "/confirmation",
  CHECKER: "/checker/:hash",
  GOOGLE_AUTH: "/google/auth/:token/:userData",
  CONSULTANT_SUMMARY: "/consultant-summary/:id/:tab",
  CONTRACTOR_PAYMENT: "/contractor-payment/:id/:tab",

  CONTRACTOR_SUMMARY: "/contractor-summary/:id/:tab",
  CLIENT_SUMMARY: "/client-summary/:id/:tab",

  CONTRACT_SUMMARY: "/contract-summary",
  CONTRACT_BOQ: "/contract-boq",
  VARIATION: "/variation",
  WORK_ITEM: "/work-item",
  MASTER_SCHEDULE: "/master-schedule",
  MASTER_SCHEDULE_SUMMARY: "/master-schedule/:id/:tab",
  PLANS: "/plans",
  REPORTS: "/reports",
  CASH_FLOW: "/cash-flow",
  PRICE_ESCALATION: "/price-escalation",
  EXECUTED_SUMMARY: "/executed-summary",
  MEASUREMENT_CERTIFICATE: "/measurement-certificate",
  PAYMENT_CERTIFICATE: "/payment-certificate",
  REQUESTED_PAYMENTS: "/requested-payments",
  ANALYTICS: "/analytics",
  EDIT: "/edit",
  WEEK_REPORTS: "/week_reports",
  PLANNING: "/planning",
  ITEM_GROUP: "/item-group",
  // PROJECT_MONTHLY_REPORT: "/project_monthly_report",
  // DESIGN_CHANGE_LOG: "/design_change_log",
  // PROJECT_VARIATION: "/project-variation",
  // CONTRACT: "/HR/Contract",
  // ID: "/HR/ID",

  EMPLOYEE_APPLICATION: "/welcome/:jobId",
  EMPLOYEE_APPLICATION2: "/apply/:jobId",
  EMPLOYEE_APPLICATION_SUCCESS: "/application/success",

  /**
   * Error
   */
  INTERNAL_SERVER_ERROR: "500",
  /**
   * Test
  //  */

  SIGN_UP: "/sign-up",
  HOME_PAGE: "/home",
  COMMUNICATION: "/communication",
};

export const PlanningTabs = {
  EMPLOYER_REQUIREMENT: "Employer Requirement",
  COST_ESTIMATION: "Cost Estimation",
  TENDER_DOCUMENT: "Tender Document",
  DRAWINGS: "Drawings",
  CONTRACT: "Contract",
};

export const ContractAdministrationTabs = {
  CONTRACT_ADMINISTRATION: "Contract Administration",
  VARIATION: "Variation",
  EXTERNAL_DOCUMENT: "External Document",
  PAYMENT: "Payment",
};

export const ProjectTaskFollowUpTabs = {
  CATEGORY: "Category",
  FOLLOW_UP: "Follow Up",
};

export const FEATURES = [
  {
    path: "design/structural/checklist-forms",
    name: "Checklist Forms",
    menu: "structural",
    header: "design",
    tab: "checklist-forms",
    key: 1,
  },
  {
    path: "design/structural/checklist",
    name: "Checklist",
    menu: "structural",
    header: "design",
    tab: "checklist",
    key: 2,
  },
  {
    path: "design/structural/file-storage",
    name: "File Storage",
    menu: "structural",
    header: "design",
    tab: "file-storage",
    key: 3,
  },

  {
    path: "design/architecture/checklist-forms",
    name: "Checklist Forms",
    menu: "architecture",
    header: "design",
    tab: "checklist-forms",
    key: 4,
  },
  {
    path: "design/architecture/checklist",
    name: "Checklist",
    menu: "architecture",
    header: "design",
    tab: "checklist",
    key: 5,
  },
  {
    path: "design/architecture/file-storage",
    name: "File Storage",
    menu: "architecture",
    header: "design",
    tab: "file-storage",
    key: 6,
  },

  {
    path: "design/plumbing/checklist-forms",
    name: "Checklist Forms",
    menu: "plumbing",
    header: "design",
    tab: "checklist-forms",
    key: 7,
  },
  {
    path: "design/plumbing/checklist",
    name: "Checklist",
    menu: "plumbing",
    header: "design",
    tab: "checklist",
    key: 8,
  },
  {
    path: "design/plumbing/file-storage",
    name: "File Storage",
    menu: "plumbing",
    header: "design",
    tab: "file-storage",
    key: 9,
  },

  {
    path: "design/mechanical/checklist-forms",
    name: "Checklist Forms",
    menu: "mechanical",
    header: "design",
    tab: "checklist-forms",
    key: 10,
  },
  {
    path: "design/mechanical/checklist",
    name: "Checklist",
    menu: "mechanical",
    header: "design",
    tab: "checklist",
    key: 11,
  },
  {
    path: "design/mechanical/file-storage",
    name: "File Storage",
    menu: "mechanical",
    header: "design",
    tab: "file-storage",
    key: 12,
  },

  {
    path: "design/electrical/checklist-forms",
    name: "Checklist Forms",
    menu: "electrical",
    header: "design",
    tab: "checklist-forms",
    key: 13,
  },
  {
    path: "design/electrical/checklist",
    name: "Checklist",
    menu: "electrical",
    header: "design",
    tab: "checklist",
    key: 14,
  },
  {
    path: "design/electrical/file-storage",
    name: "File Storage",
    menu: "electrical",
    header: "design",
    tab: "file-storage",
    key: 15,
  },

  {
    path: "design/fire-fighting/checklist-forms",
    name: "Checklist Forms",
    menu: "fire-fighting",
    header: "design",
    tab: "checklist-forms",
    key: 16,
  },
  {
    path: "design/fire-fighting/checklist",
    name: "Checklist",
    menu: "fire-fighting",
    header: "design",
    tab: "checklist",
    key: 17,
  },
  {
    path: "design/fire-fighting/file-storage",
    name: "File Storage",
    menu: "fire-fighting",
    header: "design",
    tab: "file-storage",
    key: 18,
  },

  {
    path: "design/special-system/checklist-forms",
    name: "Checklist Forms",
    menu: "special-system",
    header: "design",
    tab: "checklist-forms",
    key: 19,
  },
  {
    path: "design/special-system/checklist",
    name: "Checklist",
    menu: "special-system",
    header: "design",
    tab: "checklist",
    key: 20,
  },
  {
    path: "design/special-system/file-storage",
    name: "File Storage",
    menu: "special-system",
    header: "design",
    tab: "file-storage",
    key: 21,
  },

  {
    path: "design/sanitary/checklist-forms",
    name: "Checklist Forms",
    menu: "sanitary",
    header: "design",
    tab: "checklist-forms",
    key: 22,
  },
  {
    path: "design/sanitary/checklist",
    name: "Checklist",
    menu: "sanitary",
    header: "design",
    tab: "checklist",
    key: 23,
  },
  {
    path: "design/sanitary/file-storage",
    name: "File Storage",
    menu: "sanitary",
    header: "design",
    tab: "file-storage",
    key: 24,
  },

  {
    path: "boq/*/boq",
    name: "BoQ",
    menu: "*",
    header: "design",
    tab: "boq",
    key: 25,
  },
  {
    path: "supervision/kling-material-approval/kling-material-approval",
    name: "Kling Material Approval",
    menu: "kling-material-approval",
    header: "supervision",
    tab: "kling-material-approval",
    key: 26,
  },
  {
    path: "supervision/minutes-of-meeting/minutes-of-meeting",
    name: "Minutes of Meeting ",
    menu: "minutes-of-meeting",
    header: "supervision",
    tab: "minutes-of-meeting",
    key: 27,
  },
  {
    path: "supervision/minutes-of-meeting/minutes-of-meeting-(signed)",
    name: "Minutes of Meeting (Signed) ",
    menu: "minutes-of-meeting",
    header: "supervision",
    tab: "minutes-of-meeting-(signed)",
    key: 28,
  },

  {
    path: "supervision/site-handover/site-handover",
    name: "Site Handover",
    menu: "site-handover",
    header: "supervision",
    tab: "site-handover",
    key: 29,
  },

  {
    path: "supervision/site-diary/site-diary",
    name: "Site Diary",
    menu: "site-diary",
    header: "supervision",
    tab: "site-diary",
    key: 30,
  },
  {
    path: "supervision/site-diary/site-diary-(files)",
    name: "Site Diary (Files)",
    menu: "site-diary",
    header: "supervision",
    tab: "site-diary-(files)",
    key: 31,
  },
  {
    path: "supervision/submittal/submittal",
    name: "Submittal",
    menu: "submittal",
    header: "supervision",
    tab: "submittal",
    key: 32,
  },
  {
    path: "supervision/inspection/inspection-forms",
    name: "Inspection Forms",
    menu: "inspection",
    header: "supervision",
    tab: "inspection-forms",
    key: 33,
  },
  {
    path: "supervision/inspection/inspection",
    name: "Inspection",
    menu: "inspection",
    header: "supervision",
    tab: "inspection",
    key: 34,
  },
  {
    path: "supervision/inspection/work-permit",
    name: "Work Permit",
    menu: "inspection",
    header: "supervision",
    tab: "work-permit",
    key: 35,
  },

  {
    path: "supervision/inspection/inspection-(file)",
    name: "Inspection (File)",
    menu: "inspection",
    header: "supervision",
    tab: "inspection-(file)",
    key: 36,
  },
  {
    path: "supervision/material-test/request-for-test",
    name: "Request For Test",
    menu: "material-test",
    header: "supervision",
    tab: "request-for-test",
    key: 37,
  },
  {
    path: "supervision/material-test/casting",
    name: "Casting",
    menu: "material-test",
    header: "supervision",
    tab: "casting",
    key: 38,
  },

  {
    path: "supervision/material-test/test-results",
    name: "Test Results",
    menu: "material-test",
    header: "supervision",
    tab: "test-results",
    key: 39,
  },

  {
    path: "supervision/material-test/test-evaluation",
    name: "Test Evaluation",
    menu: "material-test",
    header: "supervision",
    tab: "test-evaluation",
    key: 40,
  },
  {
    path: "supervision/material-approval/material-approval",
    name: "Material Approval",
    menu: "material-approval",
    header: "supervision",
    tab: "material-approval",
    key: 41,
  },
  {
    path: "supervision/material-approval/material-approval-(files)",
    name: "Material Approval (Files)",
    menu: "material-approval",
    header: "supervision",
    tab: "material-approval-(files)",
    key: 42,
  },

  {
    path: "supervision/reports/weekly-plan",
    name: "Weekly Plan",
    menu: "reports",
    header: "supervision",
    tab: "weekly-plan",
    key: 43,
  },
  {
    path: "supervision/reports/weekly-report",
    name: "Weekly Report",
    menu: "reports",
    header: "supervision",
    tab: "weekly-report",
    key: 44,
  },
  {
    path: "supervision/reports/monthly-report",
    name: "Monthly Report",
    menu: "reports",
    header: "supervision",
    tab: "monthly-report",
    key: 45,
  },
  {
    path: "supervision/reports/photos-and-videos",
    name: "Photos And Videos",
    menu: "reports",
    header: "supervision",
    tab: "photos-and-videos",
    key: 46,
  },
  {
    path: "supervision/reports/summary-report",
    name: "Summary Report",
    menu: "reports",
    header: "supervision",
    tab: "summary-report",
    key: 47,
  },
  {
    path: "supervision/payment/payment-request",
    name: "Payment Request",
    menu: "payment",
    header: "supervision",
    tab: "payment-request",
    key: 48,
  },
  {
    path: "supervision/payment/payment",
    name: "Payment",
    menu: "payment",
    header: "supervision",
    tab: "payment",
    key: 49,
  },
  {
    path: "supervision/data/data",
    name: "Data",
    menu: "data",
    header: "supervision",
    tab: "data",
    key: 50,
  },
  {
    path: "supervision/site-book/site-book",
    name: "Site Book",
    menu: "site-book",
    header: "supervision",
    tab: "site-book",
    key: 51,
  },
  {
    path: "contract-administration/*/contract-administration",
    name: "Contract Administration",
    menu: "*",
    header: "contract-administration",
    tab: "contract-administration",
    key: 52,
  },
  {
    path: "detail/*/detail",
    name: "Detail",
    menu: "*",
    header: "detail",
    tab: "detail",
    key: 53,
  },
  {
    path: "supervision/monthly-reports/monthly-reports",
    name: "Monthly Reports",
    menu: "monthly-reports",
    header: "supervision",
    tab: "monthly-reports",
    key: 54,
  },
  {
    path: "supervision/project-variation/project-variation",
    name: " Project Variation",
    menu: "project-variation",
    header: "supervision",
    tab: "project-variation",
    key: 55,
  },
];
