import { ApiCallState } from "../../Utils";
import { ProjectBoardTask } from "../ProjectBoardTask/ProjectBoardTask.type";

export type ProjectCategoryBoard = {
  id: number;
  title: string;
  category_id: number;
  priority: number;
  board_tasks: ProjectBoardTask[];
};

export type ProjectCategoryBoardStateTypes = {
  fetchAll: ApiCallState<ProjectCategoryBoard[]>;
  fetchOne: ApiCallState<ProjectCategoryBoard | {}>;
  fetchLoggedIn: ApiCallState<ProjectCategoryBoard | {}>;
  fetchFeature:ApiCallState<ProjectCategoryBoard|{}>;
};

export const ProjectCategoryBoardActionTypes = {
  FETCH_ALL_PROJECT_CATEGORY_BOARD: "FETCH_ALL_PROJECT_CATEGORY_BOARD",
  FETCH_ALL_PROJECT_CATEGORY_BOARD_RESET: "FETCH_ALL_PROJECT_CATEGORY_BOARD_RESET",
  FETCH_ALL_PROJECT_CATEGORY_BOARD_FAILURE: "FETCH_ALL_PROJECT_CATEGORY_BOARD_FAILURE",
  FETCH_ALL_PROJECT_CATEGORY_BOARD_SUCCESS: "FETCH_ALL_PROJECT_CATEGORY_BOARD_SUCCESS",

  FETCH_ONE_PROJECT_CATEGORY_BOARD: "FETCH_ONE_PROJECT_CATEGORY_BOARD",
  FETCH_ONE_PROJECT_CATEGORY_BOARD_RESET: "FETCH_ONE_PROJECT_CATEGORY_BOARD_RESET",
  FETCH_ONE_PROJECT_CATEGORY_BOARD_FAILURE: "FETCH_ONE_PROJECT_CATEGORY_BOARD_FAILURE",
  FETCH_ONE_PROJECT_CATEGORY_BOARD_SUCCESS: "FETCH_ONE_PROJECT_CATEGORY_BOARD_SUCCESS",

  FETCH_LOGGED_IN_PROJECT_CATEGORY_BOARD: "FETCH_LOGGED_IN_PROJECT_CATEGORY_BOARD",
  FETCH_LOGGED_IN_PROJECT_CATEGORY_BOARD_RESET: "FETCH_LOGGED_IN_PROJECT_CATEGORY_BOARD_RESET",
  FETCH_LOGGED_IN_PROJECT_CATEGORY_BOARD_FAILURE: "FETCH_LOGGED_IN_PROJECT_CATEGORY_BOARD_FAILURE",
  FETCH_LOGGED_IN_PROJECT_CATEGORY_BOARD_SUCCESS: "FETCH_LOGGED_IN_PROJECT_CATEGORY_BOARD_SUCCESS",

  FETCH_FEATURE_PROJECT_CATEGORY_BOARD: "FETCH_FEATURE_PROJECT_CATEGORY_BOARD",
  FETCH_FEATURE_PROJECT_CATEGORY_BOARD_RESET: "FETCH_FEATURE_PROJECT_CATEGORY_BOARD_RESET",
  FETCH_FEATURE_PROJECT_CATEGORY_BOARD_FAILURE: "FETCH_FEATURE_PROJECT_CATEGORY_BOARD_FAILURE",
  FETCH_FEATURE_PROJECT_CATEGORY_BOARD_SUCCESS: "FETCH_FEATURE_PROJECT_CATEGORY_BOARD_SUCCESS",
};
