import { ApiCallState, PagedData } from "../Utils";

export type SubCategory = {
  id?: number;
  key?: any;
  description: string;
  category_id: number;
};

export type SubCategoryStateTypes = {
  fetchAll: ApiCallState<SubCategory[]>;
  fetchOne: ApiCallState<SubCategory | {}>;
  fetchPaged: ApiCallState<PagedData<SubCategory[]>>;
};

export const SubCategoryActionTypes = {
  FETCH_ALL_SUB_CATEGORY: "FETCH_ALL_SUB_CATEGORY",
  FETCH_ALL_SUB_CATEGORY_RESET: "FETCH_ALL_SUB_CATEGORY_RESET",
  FETCH_ALL_SUB_CATEGORY_FAILURE: "FETCH_ALL_SUB_CATEGORY_FAILURE",
  FETCH_ALL_SUB_CATEGORY_SUCCESS: "FETCH_ALL_SUB_CATEGORY_SUCCESS",

  FETCH_PAGED_SUB_CATEGORY: "FETCH_PAGED_SUB_CATEGORY",
  FETCH_PAGED_SUB_CATEGORY_RESET: "FETCH_PAGED_SUB_CATEGORY_RESET",
  FETCH_PAGED_SUB_CATEGORY_FAILURE: "FETCH_PAGED_SUB_CATEGORY_FAILURE",
  FETCH_PAGED_SUB_CATEGORY_SUCCESS: "FETCH_PAGED_SUB_CATEGORY_SUCCESS",

  FETCH_ONE_SUB_CATEGORY: "FETCH_ONE_SUB_CATEGORY",
  FETCH_ONE_SUB_CATEGORY_RESET: "FETCH_ONE_SUB_CATEGORY_RESET",
  FETCH_ONE_SUB_CATEGORY_FAILURE: "FETCH_ONE_SUB_CATEGORY_FAILURE",
  FETCH_ONE_SUB_CATEGORY_SUCCESS: "FETCH_ONE_SUB_CATEGORY_SUCCESS",
};
