import { ApiCallState, PagedData } from "../Utils";

export type ProjectDuration = {
  id?: number;
  key?: any;
  project_id: number;
  site_hand_over_date: string;
  mobilization_period: string;
};

export type ProjectDurationStateTypes = {
  fetchAll: ApiCallState<ProjectDuration[]>;
  fetchOne: ApiCallState<ProjectDuration | {}>;
  fetchPaged: ApiCallState<PagedData<ProjectDuration[]>>;
};

export const ProjectDurationActionTypes = {
  FETCH_ALL_PROJECT_DURATION: "FETCH_ALL_PROJECT_DURATION",
  FETCH_ALL_PROJECT_DURATION_RESET: "FETCH_ALL_PROJECT_DURATION_RESET",
  FETCH_ALL_PROJECT_DURATION_FAILURE: "FETCH_ALL_PROJECT_DURATION_FAILURE",
  FETCH_ALL_PROJECT_DURATION_SUCCESS: "FETCH_ALL_PROJECT_DURATION_SUCCESS",

  FETCH_PAGED_PROJECT_DURATION: "FETCH_PAGED_PROJECT_DURATION",
  FETCH_PAGED_PROJECT_DURATION_RESET: "FETCH_PAGED_PROJECT_DURATION_RESET",
  FETCH_PAGED_PROJECT_DURATION_FAILURE: "FETCH_PAGED_PROJECT_DURATION_FAILURE",
  FETCH_PAGED_PROJECT_DURATION_SUCCESS: "FETCH_PAGED_PROJECT_DURATION_SUCCESS",

  FETCH_ONE_PROJECT_DURATION: "FETCH_ONE_PROJECT_DURATION",
  FETCH_ONE_PROJECT_DURATION_RESET: "FETCH_ONE_PROJECT_DURATION_RESET",
  FETCH_ONE_PROJECT_DURATION_FAILURE: "FETCH_ONE_PROJECT_DURATION_FAILURE",
  FETCH_ONE_PROJECT_DURATION_SUCCESS: "FETCH_ONE_PROJECT_DURATION_SUCCESS",
};
