import { ApiCallState, PagedData } from "../Utils";

export type TimeExtension = {
  id?: number;
  key?: number | any;
  description: string;
  revised_completion_date: string | any;
  no_of_days: number;
  project_id: number;
};

export type TimeExtensionStateTypes = {
  fetchAll: ApiCallState<TimeExtension[]>;
  fetchOne: ApiCallState<TimeExtension | {}>;
  fetchPaged: ApiCallState<PagedData<TimeExtension[]>>;
};

export const TimeExtensionActionTypes = {
  FETCH_ALL_TIME_EXTENSION: "FETCH_ALL_TIME_EXTENSION",
  FETCH_ALL_TIME_EXTENSION_RESET: "FETCH_ALL_TIME_EXTENSION_RESET",
  FETCH_ALL_TIME_EXTENSION_FAILURE: "FETCH_ALL_TIME_EXTENSION_FAILURE",
  FETCH_ALL_TIME_EXTENSION_SUCCESS: "FETCH_ALL_TIME_EXTENSION_SUCCESS",

  FETCH_PAGED_TIME_EXTENSION: "FETCH_PAGED_TIME_EXTENSION",
  FETCH_PAGED_TIME_EXTENSION_RESET: "FETCH_PAGED_TIME_EXTENSION_RESET",
  FETCH_PAGED_TIME_EXTENSION_FAILURE: "FETCH_PAGED_TIME_EXTENSION_FAILURE",
  FETCH_PAGED_TIME_EXTENSION_SUCCESS: "FETCH_PAGED_TIME_EXTENSION_SUCCESS",

  FETCH_ONE_TIME_EXTENSION: "FETCH_ONE_TIME_EXTENSION",
  FETCH_ONE_TIME_EXTENSION_RESET: "FETCH_ONE_TIME_EXTENSION_RESET",
  FETCH_ONE_TIME_EXTENSION_FAILURE: "FETCH_ONE_TIME_EXTENSION_FAILURE",
  FETCH_ONE_TIME_EXTENSION_SUCCESS: "FETCH_ONE_TIME_EXTENSION_SUCCESS",
};
